app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
*/

Route::get('/', ['as' => 'index', 'uses' => 'WelcomeController@index']);

Route::get('home', 'WelcomeController@redirectHome');

get('angular-ui-notification.html', 'ViewHandlerController@angularUiNotificationView');

get(config('okie.privacy_policy.url'), 'WelcomeController@getPrivacyPolicy');
get(config('okie.terms_and_conditions.url'), 'WelcomeController@getTermsAndConditions');

Route::get('permission', 'UserController@getPermission');

Route::controller('test', 'TestController');

Route::get('/testing/force-login/{id}', 'TestController@forceLogin');

Route::get('banners', ['as' => 'banner', 'uses' => 'WelcomeController@getAllBanads']);

// Route::controllers([
//  'auth' => 'Auth\AuthController',
//  'password' => 'Auth\PasswordController',
// ]);

Route::controller('auth', 'Auth\AuthController', [
    'getLogin' => 'auth.login',
    'postLogin' => 'auth.login.post'
]);

Route::get( 'login', 'WelcomeController@redirectLogin');

Route::get('routes', 'HomeController@getAllRoutes');

Route::get('i', ['as' => 'i', 'uses' => 'UserController@getUserInfo']);

Route::get( 'login/{provider?}', ['as' => 'login.provider', 'uses' => 'Auth\AuthController@login'] );


Route::get('messages', ['as' => 'messages', 'uses' => 'HomeController@messages', 'middleware' => 'admin']);

// Route for Products
Route::resource('product', 'ProductController',
[
    'names' => [
        'create' => 'product.add'
    ]
]);
Route::match(['post', 'put', 'patch'], 'product/{product}/category', ['as' => 'product.update.category', 'uses' => 'ProductController@updateCategory']);
Route::post('product/{id}/add-image', ['as' => 'product.add_image.post', 'uses' => 'ProductController@addImagePost']);
Route::get('product/{product}/images', ['as' => 'product.images', 'uses' => 'ProductController@showImages']);
Route::get('product/views/lightbox.html', 'ProductController@getLightboxView');
Route::match(['post', 'delete'], 'product/{product}/images', ['as' => 'product.images.post', 'uses' => 'ProductController@postImages']);
Route::match(['post', 'put', 'patch'], 'product/{product}/badge', ['as' => 'product.update.badge', 'uses' => 'ProductController@updateBadge']);
Route::match(['post', 'put', 'patch'], 'product/{product}/badge/remove', ['as' => 'product.update.badge.remove', 'uses' => 'ProductController@removeBadge']);

Route::group(['prefix' => 'views'], function()
{
    // Route::get('index.html', 'WelcomeController@getIndexView');
    // Route::get('products/category.html', function(){ return view( 'product.a_category' ); });
    // Route::get('products/index.html', function(){ return view( 'product.a_index'); });
    // Route::get('settings/index.html', function(){ return view( 'settings.a_index' ); });
    get('{view}.html', 'ViewHandlerController@getIndexPublicView');

    // get('settings/{view}.html', ['uses' => 'SettingsController@getPublicView', 'middleware' => 'admin']);
    get('{type}/{view}.html', 'ViewHandlerController@getPublicView');
    // get('messages/messages.html', 'MessageController@getMessagesView');
    // get('messages/conversation.html', 'MessageController@getConversationView');
    // get('messages/conversation_delivered.html', 'MessageController@getConversationDeliveredView');
    // get('messages/create.html', 'MessageController@getCreateView');
    
});

Route::group(['prefix' => 'search'], function()
{
    Route::get('user/{search?}', ['as' => 'search.user', 'uses' => 'SearchController@getUser']);
    Route::get('product/{search?}', ['as' => 'search.product', 'uses' => 'SearchController@getProduct']);
});

Route::post('newsletter', ['as' => 'newsletter', 'uses' => 'NewsletterController@subscribeToNewsletter']);
Route::get('newsletter', ['as' => 'newsletter.user', 'uses' => 'NewsletterController@getSubscribeByUser']);

Route::group(['prefix' => 'me', 'middleware' => 'auth'], function()
{
    Route::get('/', ['as' => 'me', 'uses' => 'UserController@getUserInfo']);
    Route::get('friends', ['as' => 'me.friends', 'uses' => 'UserController@getFriendsList']);
    Route::get('banners', ['as' => 'me.banners', 'uses' => 'OptionController@getAllBanads']);
    Route::get('views/{view}.html', 'ViewHandlerController@getMessagesView');
    Route::group(['prefix' => 'settings'], function()
    {
        Route::get('/', ['as' => 'settings.index', 'uses' => 'SettingsController@index']);
        Route::post('newsletter', ['as' => 'settings.newsletter.unsubscribe', 'uses' => 'NewsletterController@unsubscribeEmail']);
        Route::patch('permissions', ['as' => 'settings.permissions', 'uses' => 'SettingsController@changeUserPermission']);
        Route::post('general', ['as' => 'settings.general', 'uses' => 'OptionController@updateAppConfig']);
        Route::get('banners', ['as' => 'settings.banners', 'uses' => 'OptionController@getAllBanads']);
        Route::post('banner', ['as' => 'settings.banner', 'uses' => 'OptionController@addBanner']);
        Route::delete('banner/{id}', ['as' => 'settings.banner.delete', 'uses' => 'OptionController@removeBanad']);
    });
    Route::group(['prefix' => 'products'], function()
    {
        Route::get('/', ['as' => 'products.index', 'uses' => 'ProductController@index']);
        Route::get('categories', ['as' => 'products.categories', 'uses' => 'CategoryController@getCategories']);
        Route::post('categories', ['as' => 'products.categories.post', 'uses' => 'CategoryController@postCategory']);
    });
    Route::group(['prefix' => 'messages'], function()
    {
        Route::get('/', ['as' => 'messages.index', 'uses' => 'MessageController@index']);
        Route::get('offset', ['as' => 'messages.offset', 'uses' => 'ThreadController@getMessagesByOffset']);
        Route::post('create', ['as' => 'messages.create', 'uses' => 'MessageController@createMessage']);
        Route::group(['prefix' => 'inquiry'], function()
        {
            get('all', ['as' => 'inquiry.all', 'uses' => 'InquiryController@getAll']);
            get('{inquiry_id}', ['as' => 'inquiry', 'uses' => 'InquiryController@get']);
            get('{inquiry_id}/conversations', ['as' => 'inquiry.conversations', 'uses' => 'InquiryController@getConversations']);
            post('reply', ['as' => 'inquiry.reply', 'uses' => 'InquiryController@reply']);
            post('replyReceipt', ['as' => 'inquiry.replyReceipt', 'uses' => 'InquiryController@replyReceipt']);
            post('reserve', ['as' => 'inquiry.reserve', 'uses' => 'InquiryController@postReserve']);
            post('delivered', ['as' => 'inquiry.delivered', 'uses' => 'DeliverController@create']);
            post('receipt', ['as' => 'inquiry.receipt', 'uses' => 'InquiryController@toggleUpload']);
            get('product/{product_id}', ['as' => 'inquiry.product', 'uses' => 'InquiryController@getInquiryByProduct']);
        });
        Route::group(['prefix' => 'inbox'], function()
        {
            get('/', ['as' => 'messages.inbox', 'uses' => 'InboxController@getAll']);
            get('all', ['as' => 'inbox.all', 'uses' => 'InboxController@getAll']);
            get('{inbox_id}', ['as' => 'inbox', 'uses' => 'InboxController@get']);
            get('{inbox_id}/conversations', ['as' => 'inbox.conversations', 'uses' => 'InboxController@getConversations']);
            post('reply', ['as' => 'inbox.reply', 'uses' => 'InboxController@reply']);
            post('create', ['as' => 'inbox.create', 'uses' => 'InboxController@create']);
            post('{conversation_id}/delete', ['as' => 'inbox.remove.conversation', 'uses' => 'InboxController@destroyConversation']);
        });
        Route::group(['prefix' => 'delivered'], function()
        {
            get('/', ['as' => 'messages.delivered', 'uses' => 'DeliverController@getAll']);
            get('all', ['as' => 'delivered.all', 'uses' => 'DeliverController@getAll']);
            get('{delivered_id}', ['as' => 'delivered', 'uses' => 'DeliverController@get']);
            get('{delivered_id}/conversations', ['as' => 'delivered.conversations', 'uses' => 'DeliverController@getConversations']);
            post('reply', ['as' => 'delivered.reply', 'uses' => 'DeliverController@reply']);
        });
        Route::get('inquiries', ['as' => 'messages.inquiries', 'uses' => 'InquiryController@getAll']);
        // Route::get('inquire/{thread_id}', ['as' => 'messages.inquiries.thread', 'uses' => 'ThreadController@getInquiryByThread']);
        // Route::get('inquire/{thread_id}/messages', ['as' => 'messages.inquiries.thread.messages', 'uses' => 'ThreadController@getMessagesByThread']);
        // Route::post('inquire/reply', ['as' => 'messages.inquiries.reply', 'uses' => 'MessageController@replyToInquire']);
        // Route::post('inquire/delivered', ['as' => 'messages.inquiries.delivered', 'uses' => 'ThreadController@updateToDelivered']);

        //Route::get('delivered', ['middleware' => 'admin', 'as' => 'messages.delivered', 'uses' => 'ThreadController@getAllDelivered']);
    });
    Route::group(['prefix' => 'reviews'], function()
    {
        get('/', ['as' => 'reviews.index', 'uses' => 'ReviewController@getAll']);
        post('{id}/approved', ['as' => 'reviews.approved', 'uses' => 'ReviewController@approvedReview']);
        post('{id}/unapproved', ['as' => 'reviews.unapproved', 'uses' => 'ReviewController@unapprovedReview']);
    });
});

Route::group(['prefix' => 'items'], function()
{
    Route::get('/', ['as' => 'items.index', 'uses' => 'ItemController@index']);
    Route::get('/{id}', ['as' => 'items.item', 'uses' => 'ItemController@show'])->where( 'id', '[0-9]+' );
    Route::get('/category/{id}', ['as' => 'items.category', 'uses' => 'ItemController@showByCategory']);
});

Route::group(['prefix' => 'item'], function()
{
    get('/{id}', ['as' => 'item.show', 'uses' => 'ItemController@show']);

resources/views/a_home.blade.php
<div class="container content-container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
					You are logged in!
				</div>
			</div>
		</div>
	</div>
</div>

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en" @yield('html.attr')>
<head @yield('head.attr')>
	@yield('head.pre')
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<title>{{ config('app.title') }} @yield('title')</title>
	
	<link href="{{ asset('/vendor/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css" />
	<link href="{{ asset('/css/app.css') }}" rel="stylesheet" type="text/css" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
	@yield('head.post')
</head>
<body @yield('body.attr')>
	@yield('body.pre')
	<nav class="navbar navbar-default navbar-fixed-top" id="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a ng-click="collapseToggle()" class="navbar-brand" href="{{ route('index') }}/#/">
					<img src="{{ asset('images/logo.png') }}" alt="logo" /> {{ config('app.logo.name') }}
				</a>
			</div>

			<div class="collapse navbar-collapse" id="navbar-collapse-1">
				<div class="okie-search">LOADING...</div>
				
				@include( 'templates.navigation', [ 'categories' => \Okie\Category::all() ] )

				<ul class="nav navbar-nav navbar-right text-center">
					@if ( Auth::guest() )
						<li><a class="btn facebook color" href="{{ url( '/login/facebook' ) }}"><i class="fa fa-facebook-official"></i> Login with Facebook</a></li>
					@else
						@if( Auth::user()->isAdmin() )
						<li>
							<a href="{{ route('product.add') }}" data-toggle="tooltip" data-placement="bottom" title="Add new product"><i class="fa fa-plus text-success"></i></a>
						</li>
						@endif
						<li class="with-notification">
							<a data-notify="message" class="with-tooltip" data-toggle="tooltip" data-placement="bottom" title="See messages only" href="{{ route('messages.index') }}#inquiries">
								<i class="fa fa-envelope"></i><span class="badge badge-danger"></span>
							</a>
						</li>
						@if( Auth::user()->isAdmin() )
						<li class="with-notification">
							<a id="notify_notifications" data-toggle="tooltip" data-placement="bottom" title="Check your notifications" href="/#!/notifications">
								<i class="fa fa-bell"></i><span class="badge"></span>
							</a>
						</li>
						@endif
						<li class="dropdown">
							<a href="{{ route('me') }}" class="user user-avatar dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
								<img src="{{ Auth::user()->avatar}}" alt="avatar" />{{ Auth::user()->first_name }} 
								<i class="fa fa-caret-up icon-up"></i>
								<i class="fa fa-caret-down icon-down"></i>
							</a>
							<ul class="dropdown-menu" role="menu">
								<li role="presentation" class="text-center dropdown-header">Account</li>
								<li><a href="{{ route('me') }}">Profile</a></li>
								<li><a href="{{ route('messages.index') }}{# $state.href('messages.inquiries') #}">Messages</a></li>
								<li><a href="{{ route('settings.index') }}{# $state.href('settings.newsletter') #}">Settings</a></li>
								@if ( Auth::user()->isAdmin() )
								<li><a href="{{ route('products.index') }}{# $state.href('products.all') #}">Products</a></li>
								@endif
								<li class="divider"></li>
								<li><a href="{{ url('/auth/logout') }}">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

	@include('templates.heading')
	
	@yield('content')

@include('templates.footer', [ 'products' => \Okie\Product::getFeatured( 20 ) ])

	<!-- Scripts -->
	<!-- <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->
	<!-- <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script> -->
	<script src="{{ asset('/vendor/jquery/jquery.min.js') }}"></script>
	<script src="{{ asset('/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
	<script src="{{ asset('/vendor/angular/angular.js') }}"></script>
	<script src="{{ asset('/js/vendor.js') }}"></script>
	<script src="{{ asset('/js/scripts.js') }}"></script>

	@yield('body.post')

	@if( Session::has( 'message' ) )
	<script type="text/javascript">
	angular.element( 'body' ).ready(function(){ Notification.success({ title: 'Hi!', message: '{{ Session::get( 'message' ) }}' }); });
	</script>
	@endif
</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')

<div class="content-container home-container">
	
	@include( 'templates.navigation-categories', [ 'categories' => \Okie\Category::all() ] )

	@section( 'main-content' )
	<div ui-view></div>
	<div ui-view="banner" class="banner 
	@if( config('okie.banner.full_width') )
	full-width
	@else
	container
	@endif
	"></div>
	<div ui-view="items">
		
		<div class="center-block text-center page-header">
			<h1>LOADING</h1>
		</div>

	</div>
	@show

</div>

@endsection

resources/views/index.blade.php
<div class="container content-container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Home</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/item.blade.php
@extends('home')

@section('html.attr', 'prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# product: http://ogp.me/ns/product#"')


@section('head.pre')

<meta property="og:type" content="product" />
<meta property="og:title" content="{{ config('app.title') }} - {{ $product->name }}" />
<meta property="og:image" content="{{ $product->thumbnail[2]['url'] }}" />
@foreach ( $product->images as $key => $value)
<meta property="og:image" content="{{ $value->sizes[2]['url'] }}" />
@endforeach
<meta property="og:description" content="{!! str_replace( ['</p><p>','<br/>','<p>','</p>'], ["\r\n","\r\n",'',''], preg_replace("/<([a-z][a-z0-9]*)[^>]*?(\/?)>/i",'<$1$2>',strip_tags( $product->description, '<br><p>' ) ) ) !!}" />
<meta property="og:updated_time" content="{{ $product->updated_at }}" />
@foreach ( $product->related as $key => $value)
<meta property="og:see_also" content="{{ route('item.show', $value->id) }}" />
@endforeach
<meta property="product:category" content="{{ ( !empty( $product->categories()->first() ) ? $product->categories()->first()->name : 'All' ) }}" />

<meta property="product:original_price:amount" content="{{ $product->price }}" />
<meta property="product:original_price:currency" content="Php" />
<meta property="product:price:amount" content="{{ $product->price }}" />
<meta property="product:price:currency" content="Php" />
<meta property="product:sale_price:amount" content="{{ $product->sale_price }}" />
<meta property="product:sale_price:currency" content="Php" />


@stop

@section('main-content')

<div id="item_container" class="container" ng-controller="ItemController" ng-init="getItem( {{ $product->id }} )">
    <hr class="animated fadeIn" />
    <div class="item-wrapper clearfix">
        <div id="item_content_left" class="col-md-5 item-left affected-with-affix">
            <div class="item-carousel animated fadeInLeft">
                <carousel interval="carouselInterval">
                    <slide ng-repeat="image in item.images" active="image.active">
                        <img ng-click="clickImage( $index )" ng-src="{# image.sizes[2].url #}" alt="{# image.caption #}" />
                    </slide>
                </carousel>
            </div>
        </div>
        <div class="col-md-7 item-right">
            <div class="page-header" id="header">
                <h1>{{ $product->name }} <span class="small">{# item.badge.title #}</span></h1>
                <div class="item-rating">
                    <div class="rating-star"
                    @if( Auth::check() )
                    ng-click="ratingItem()" data-toggle="collapse" data-target="#ratingCollapse" aria-expanded="false" aria-controls="ratingCollapse"
                    @endif
                    >
                        <rating readonly="true" ng-model="item.rating.average" max="rating.maximum" popover-append-to-body="true" popover-placement="right" popover="The rating of the product. @if( Auth::check() ) Click if you want to rate this product @endif" popover-title="F.A.Q" title="F.A.Q" popover-trigger="mouseenter"></rating> <span class="small" ng-if="!item.rating.count">NOT YET RATED</span>
                    </div>
                    @if( Auth::check() )
                    <div class="collapse" id="ratingCollapse">
                        {!! Form::open(['ng-show' => 'ratingState', 'class' => 'animate', 'name' => 'form_rate_item', 'ng-submit' => 'form_rate_item.$valid && rateTheItem( $event, item.id )', 'route' => ['item.rate', '_ITEM_ID_']]) !!}
                        <div class="rating-star">
                            <rating ng-if="!item.review" required="required" ng-required="true" ng-model="item.rating.rating" max="rating.maximum" popover-append-to-body="true" popover-placement="right" popover="Rate this product" popover-title="F.A.Q" title="F.A.Q" popover-trigger="mouseenter"></rating> <span class="small" ng-if="!item.rating.count">BE THE FIRST TO RATE THIS PRODUCT</span>
                            <rating ng-if="item.review" required="required" ng-required="true" ng-model="item.review.rating" max="rating.maximum" popover-append-to-body="true" popover-placement="right" popover="Rate this product" popover-title="F.A.Q" title="F.A.Q" popover-trigger="mouseenter"></rating> <span ng-if="item.review" class="small">YOU CAN UPDATE YOUR RATING</span>
                        </div>
                        <div ng-if="!item.review" class="no-buttons content-description" ta-toolbar="[['p', 'undo', 'redo', 'clear']]" ng-minlength="5" placeholder="Tell us about this product" text-angular ng-model="item.rating.message"></div>
                        <div ng-if="item.review" class="no-buttons content-description" ta-toolbar="[['p', 'undo', 'redo', 'clear']]" ng-minlength="5" placeholder="Tell us about this product" text-angular ng-model="item.review.message"></div>
                        <div class="buttons">
                            <button type="button" ng-show="form_rate_item.$invalid && ! rateSubmittingState" class="btn btn-warning">SUBMIT</button>
                            <button type="submit" ng-click="form_rate_item.$valid && rateTheItem( $event, item.id )" ng-show="form_rate_item.$valid && ! rateSubmittingState" class="btn btn-success">SUBMIT</button>
                            <button type="button" ng-show="rateSubmittingState" class="btn btn-success">LOADING</button>
                            <button ng-click="ratingItem()" ng-hide="rateSubmittingState" type="button" data-toggle="collapse" data-target="#ratingCollapse" aria-expanded="false" aria-controls="ratingCollapse" class="btn btn-warning">CANCEL</button>
                        </div>
                        {!! Form::close() !!}
                    </div>
                    @endif
                </div>
            </div>
            <div class="item-info" ng-hide="inquireState">
                <div class="container-fluid row animated fadeInUp">
                    <p ng-class="{ 'item-sale': item.sale_price }" class="item-price text-primary">
                        @if( isset( $product->sale_price ) )
                            <span class="sale-price">{# {{ $product->sale_price }} | currency: "Php" #}</span>
                        @endif
                        <span class="orig-price">{# {{ $product->price }} | currency:"Php" #}</span>
                    </p>
                    <br />
                    <div class="item-description content-description">
                        <div>{!! $product->description !!}</div>
                    </div>
                    <hr />
                    @if( config('product.item.remaining') )
                    <div class="input-group input-group-sm item-unit col-md-3">
                        <span class="input-group-addon" id="sizing-addon2">REMAINING
                            <a href="javascript:void(0)" popover-append-to-body="true" popover-placement="right" popover="The availability of the product" class="fa fa-question-circle" popover-title="F.A.Q" title="F.A.Q" data-content="How many items are available" popover-trigger="mouseenter"></a>
                        </span>
                        <span class="form-control">{{ $product->unit }}</span>
                    </div>
                    <br />
                    @endif
                    @if( Auth::check() )
                        @if( Auth::user()->isUser() )
                    <div class="item-inquire">
                        <a ng-if="!item.inquiry" href="javascript:void(0)" ng-click="inquireItem()" class="btn btn-primary">INQUIRE FOR THIS PRODUCT</a>
                        <a ng-if="item.inquiry" href="{{ route('messages.index') }}{# $state.href('messages.viewInquiry', { inquiryId: item.inquiry.id }) #}" class="btn btn-success"><i class="fa fa-envelope-o"></i> READ MESSAGES</a>
                    </div>
                        @else
                    <div class="item-inquire">
                        <a href="{{ route('messages.index') }}{# $state.href('messages.inquiriesProduct', { productId: item.id } )#}" class="btn btn-primary">CHECK FOR INQUIRIES<span class="hidden-xs hidden-sm"> ON THIS PRODUCT</span></a>
                        @if( Auth::user()->isAdmin() )
                        <a href="{{ route('product.show', '') }}/{# item.id #}" class="btn btn-info">EDIT THIS PRODUCT</a>
                        @endif
                    </div>
                        @endif

                    @else
                    <div class="item-inquire">
                        <a ng-click="redirectInItem()" href="{{ route('auth.login') }}?redirect_to_item={# $stateParams.itemId #}" class="btn btn-warning">LOGIN TO INQUIRE</a>
                    </div>
                    @endif
                </div>
            </div>
            <div class="item-inquire" ng-show="inquireState">
                <alert class="animated fadeIn" ng-repeat="inquireMessage in inquireMessages" close="closeInquireMessage( $index )" type="{# inquireMessage.type #}">
                    {# inquireMessage.message #}
                </alert>
                <div class="container-fluid row animated fadeIn">
                    {!! Form::open(['route' => 'item.inquire', 'name' => 'form_inquire', 'ng-submit' => 'form_inquire.$valid && inquireSubmit( $event )']) !!}
                        <div class="col-md-8">
                            <h4>Do you want to reseve? How many do you want?</h4>
                        </div>
                        <div class="input-group col-md-4">
                            <div class="input-group-btn">
                                <button ng-click="inquire.reserve = inquire.reserve + 1" type="button" class="btn btn-primary"><i class="fa fa-plus"></i></button>
                            </div>
                            <input type="text" ng-disabled="true" ng-model="inquire.reserve" class="text-center form-control" />
                            <div class="input-group-btn">
                                <button ng-click="inquire.reserve = ( inquire.reserve > 1 ) ? inquire.reserve - 1 : inquire.reserve = 0" type="button" class="btn btn-primary"><i class="fa fa-minus"></i></button>
                            </div>
                        </div>
                        <br />
                        <div class="content-description" ta-toolbar="[['bold', 'italics', 'underline', 'undo', 'redo', 'clear']]" ng-minlength="5" required ng-required="true" placeholder="I would like to inquire about this item" text-angular ng-model="inquire.message"></div>
                        <input ng-hide="inquireSubmitButton.state" type="submit" ng-class="{ 'btn-success': form_inquire.$valid }" class="btn btn-primary btn-lg" ng-disabled="form_inquire.$invalid" value="SUBMIT" />
                        <button ng-show="inquireSubmitButton.state" type="button" class="btn btn-success btn-lg"><i class="fa fa-circle-o-notch fa-spin" ng-show="inquireSubmitButton.state"></i> SUBMITTING</button>
                        <button ng-hide="inquireSubmitButton.state" class="btn-warning btn" type="button" ng-click="inquireItem()">CANCEL</button>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
        
    </div>
    <div class="item-related clearfix">
        <hr />
        <header class="page-header">
            <h2>{{ config( 'responses.other_items' ) }}</h2>
        </header>
        <ul class="container-fluid list-unstyled item-container">
            <li ng-repeat="product in item.related" class="items-animation animate product-{# product.id #} col-md-3 product-item-related"
                data-product-id="{# product.id #}"
                data-product-name="{# product.name #}"
                data-product-code="{# product.code #}">
                
                <a class="product-item-container" href="{{ route('index' ) }}{# $state.href('item', { itemId: product.id }) #}">
                    <div ng-style="{ 'background-color': product.badge.color }" class="ribbon {# product.badge.class #} ribbon-default" ng-if="product.badge.title">
                        <span>{# product.badge.title #}</span>
                    </div>
                    <div class="img">
                        <img ng-src="{# product.thumbnail[2].url #}" alt="" class="img-responsive" />
                    </div>
                    <div class="description">
                        <em class="small content-description">{# product.categories[0].name #}</em>
                        <br />{# product.name #}
                    </div>
                </a>
            </li>
        </ul>
    </div>

    
</div>

@overwrite

resources/views/privacy_policy.blade.php
@extends('app')

@section('content')

<div class="content-container home-container home-privacy-policy privacy-policy">
	
	@include( 'templates.navigation-categories', [ 'categories' => \Okie\Category::all() ] )
	
	<div class="container content-description">
		<header class="no-margin-top page-header">
			<h1 class="no-margin">{{ $title }}</h1>
		</header>
		{!! $contents !!}
	</div>

</div>

@endsection