app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
*/

Route::get('/', ['as' => 'index', 'uses' => 'WelcomeController@index']);

Route::get('home', 'WelcomeController@redirectHome');

get('angular-ui-notification.html', 'ViewHandlerController@angularUiNotificationView');

get(config('okie.privacy_policy.url'), 'WelcomeController@getPrivacyPolicy');
get(config('okie.terms_and_conditions.url'), 'WelcomeController@getTermsAndConditions');

Route::get('permission', 'UserController@getPermission');

Route::controller('test', 'TestController');

Route::get('/testing/force-login/{id}', 'TestController@forceLogin');

Route::get('banners', ['as' => 'banner', 'uses' => 'WelcomeController@getAllBanads']);

// Route::controllers([
//  'auth' => 'Auth\AuthController',
//  'password' => 'Auth\PasswordController',
// ]);

Route::controller('auth', 'Auth\AuthController', [
    'getLogin' => 'auth.login',
    'postLogin' => 'auth.login.post'
]);

Route::get( 'login', 'WelcomeController@redirectLogin');

Route::get('routes', 'HomeController@getAllRoutes');

Route::get('i', ['as' => 'i', 'uses' => 'UserController@getUserInfo']);

Route::get( 'login/{provider?}', ['as' => 'login.provider', 'uses' => 'Auth\AuthController@login'] );


Route::get('messages', ['as' => 'messages', 'uses' => 'HomeController@messages', 'middleware' => 'admin']);

// Route for Products
Route::resource('product', 'ProductController',
[
    'names' => [
        'create' => 'product.add'
    ]
]);
Route::match(['post', 'put', 'patch'], 'product/{product}/category', ['as' => 'product.update.category', 'uses' => 'ProductController@updateCategory']);
Route::post('product/{id}/add-image', ['as' => 'product.add_image.post', 'uses' => 'ProductController@addImagePost']);
Route::get('product/{product}/images', ['as' => 'product.images', 'uses' => 'ProductController@showImages']);
Route::get('product/views/lightbox.html', 'ProductController@getLightboxView');
Route::match(['post', 'delete'], 'product/{product}/images', ['as' => 'product.images.post', 'uses' => 'ProductController@postImages']);
Route::match(['post', 'put', 'patch'], 'product/{product}/badge', ['as' => 'product.update.badge', 'uses' => 'ProductController@updateBadge']);
Route::match(['post', 'put', 'patch'], 'product/{product}/badge/remove', ['as' => 'product.update.badge.remove', 'uses' => 'ProductController@removeBadge']);

Route::group(['prefix' => 'views'], function()
{
    // Route::get('index.html', 'WelcomeController@getIndexView');
    // Route::get('products/category.html', function(){ return view( 'product.a_category' ); });
    // Route::get('products/index.html', function(){ return view( 'product.a_index'); });
    // Route::get('settings/index.html', function(){ return view( 'settings.a_index' ); });
    get('{view}.html', 'ViewHandlerController@getIndexPublicView');

    // get('settings/{view}.html', ['uses' => 'SettingsController@getPublicView', 'middleware' => 'admin']);
    get('{type}/{view}.html', 'ViewHandlerController@getPublicView');
    // get('messages/messages.html', 'MessageController@getMessagesView');
    // get('messages/conversation.html', 'MessageController@getConversationView');
    // get('messages/conversation_delivered.html', 'MessageController@getConversationDeliveredView');
    // get('messages/create.html', 'MessageController@getCreateView');
    
});

Route::group(['prefix' => 'search'], function()
{
    Route::get('user/{search?}', ['as' => 'search.user', 'uses' => 'SearchController@getUser']);
    Route::get('product/{search?}', ['as' => 'search.product', 'uses' => 'SearchController@getProduct']);
});

Route::post('newsletter', ['as' => 'newsletter', 'uses' => 'NewsletterController@subscribeToNewsletter']);
Route::get('newsletter', ['as' => 'newsletter.user', 'uses' => 'NewsletterController@getSubscribeByUser']);

Route::group(['prefix' => 'me', 'middleware' => 'auth'], function()
{
    Route::get('/', ['as' => 'me', 'uses' => 'UserController@getUserInfo']);
    Route::get('friends', ['as' => 'me.friends', 'uses' => 'UserController@getFriendsList']);
    Route::get('banners', ['as' => 'me.banners', 'uses' => 'OptionController@getAllBanads']);
    Route::get('views/{view}.html', 'ViewHandlerController@getMessagesView');
    Route::group(['prefix' => 'settings'], function()
    {
        Route::get('/', ['as' => 'settings.index', 'uses' => 'SettingsController@index']);
        Route::post('newsletter', ['as' => 'settings.newsletter.unsubscribe', 'uses' => 'NewsletterController@unsubscribeEmail']);
        Route::patch('permissions', ['as' => 'settings.permissions', 'uses' => 'SettingsController@changeUserPermission']);
        Route::post('general', ['as' => 'settings.general', 'uses' => 'OptionController@updateAppConfig']);
        Route::get('banners', ['as' => 'settings.banners', 'uses' => 'OptionController@getAllBanads']);
        Route::post('banner', ['as' => 'settings.banner', 'uses' => 'OptionController@addBanner']);
        Route::delete('banner/{id}', ['as' => 'settings.banner.delete', 'uses' => 'OptionController@removeBanad']);
    });
    Route::group(['prefix' => 'products'], function()
    {
        Route::get('/', ['as' => 'products.index', 'uses' => 'ProductController@index']);
        Route::get('categories', ['as' => 'products.categories', 'uses' => 'CategoryController@getCategories']);
        Route::post('categories', ['as' => 'products.categories.post', 'uses' => 'CategoryController@postCategory']);
    });
    Route::group(['prefix' => 'messages'], function()
    {
        Route::get('/', ['as' => 'messages.index', 'uses' => 'MessageController@index']);
        Route::get('offset', ['as' => 'messages.offset', 'uses' => 'ThreadController@getMessagesByOffset']);
        Route::post('create', ['as' => 'messages.create', 'uses' => 'MessageController@createMessage']);
        Route::group(['prefix' => 'inquiry'], function()
        {
            get('all', ['as' => 'inquiry.all', 'uses' => 'InquiryController@getAll']);
            get('{inquiry_id}', ['as' => 'inquiry', 'uses' => 'InquiryController@get']);
            get('{inquiry_id}/conversations', ['as' => 'inquiry.conversations', 'uses' => 'InquiryController@getConversations']);
            post('reply', ['as' => 'inquiry.reply', 'uses' => 'InquiryController@reply']);
            post('replyReceipt', ['as' => 'inquiry.replyReceipt', 'uses' => 'InquiryController@replyReceipt']);
            post('reserve', ['as' => 'inquiry.reserve', 'uses' => 'InquiryController@postReserve']);
            post('delivered', ['as' => 'inquiry.delivered', 'uses' => 'DeliverController@create']);
            post('receipt', ['as' => 'inquiry.receipt', 'uses' => 'InquiryController@toggleUpload']);
            get('product/{product_id}', ['as' => 'inquiry.product', 'uses' => 'InquiryController@getInquiryByProduct']);
        });
        Route::group(['prefix' => 'inbox'], function()
        {
            get('/', ['as' => 'messages.inbox', 'uses' => 'InboxController@getAll']);
            get('all', ['as' => 'inbox.all', 'uses' => 'InboxController@getAll']);
            get('{inbox_id}', ['as' => 'inbox', 'uses' => 'InboxController@get']);
            get('{inbox_id}/conversations', ['as' => 'inbox.conversations', 'uses' => 'InboxController@getConversations']);
            post('reply', ['as' => 'inbox.reply', 'uses' => 'InboxController@reply']);
            post('create', ['as' => 'inbox.create', 'uses' => 'InboxController@create']);
            post('{conversation_id}/delete', ['as' => 'inbox.remove.conversation', 'uses' => 'InboxController@destroyConversation']);
        });
        Route::group(['prefix' => 'delivered'], function()
        {
            get('/', ['as' => 'messages.delivered', 'uses' => 'DeliverController@getAll']);
            get('all', ['as' => 'delivered.all', 'uses' => 'DeliverController@getAll']);
            get('{delivered_id}', ['as' => 'delivered', 'uses' => 'DeliverController@get']);
            get('{delivered_id}/conversations', ['as' => 'delivered.conversations', 'uses' => 'DeliverController@getConversations']);
            post('reply', ['as' => 'delivered.reply', 'uses' => 'DeliverController@reply']);
        });
        Route::get('inquiries', ['as' => 'messages.inquiries', 'uses' => 'InquiryController@getAll']);
        // Route::get('inquire/{thread_id}', ['as' => 'messages.inquiries.thread', 'uses' => 'ThreadController@getInquiryByThread']);
        // Route::get('inquire/{thread_id}/messages', ['as' => 'messages.inquiries.thread.messages', 'uses' => 'ThreadController@getMessagesByThread']);
        // Route::post('inquire/reply', ['as' => 'messages.inquiries.reply', 'uses' => 'MessageController@replyToInquire']);
        // Route::post('inquire/delivered', ['as' => 'messages.inquiries.delivered', 'uses' => 'ThreadController@updateToDelivered']);

        //Route::get('delivered', ['middleware' => 'admin', 'as' => 'messages.delivered', 'uses' => 'ThreadController@getAllDelivered']);
    });
    Route::group(['prefix' => 'reviews'], function()
    {
        get('/', ['as' => 'reviews.index', 'uses' => 'ReviewController@getAll']);
        post('{id}/approved', ['as' => 'reviews.approved', 'uses' => 'ReviewController@approvedReview']);
        post('{id}/unapproved', ['as' => 'reviews.unapproved', 'uses' => 'ReviewController@unapprovedReview']);
    });
});

Route::group(['prefix' => 'items'], function()
{
    Route::get('/', ['as' => 'items.index', 'uses' => 'ItemController@index']);
    Route::get('/{id}', ['as' => 'items.item', 'uses' => 'ItemController@show'])->where( 'id', '[0-9]+' );
    Route::get('/category/{id}', ['as' => 'items.category', 'uses' => 'ItemController@showByCategory']);
});

Route::group(['prefix' => 'item'], function()
{
    get('/{id}', ['as' => 'item.show', 'uses' => 'ItemController@show']);

app/Message.php
<?php namespace Okie;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

/**
 * Okie\Message
 *
 * @property-read \Okie\User $user 
 * @property-read \Okie\Product $product 
 * @property-read mixed $time 
 * @property-read \Illuminate\Database\Eloquent\Collection|\Okie\Thread[] $thread 
 * @method static \Okie\Message inquiriesObject()
 * @method static \Okie\Message inquiries()
 * @method static \Okie\Message messagesByProduct($product_id, $user_id)
 */
class Message extends Model {

	use SoftDeletes;

	/**
	 * @var string
	 */
	protected $table = 'messages';

	/**
	 * @var array
	 */
	protected $dates = [ 'deleted_at' ];

	/**
	 * @var array
	 */
	protected $fillable = [ 'user_id', 'body', 'product_id', 'type' ];

	/**
	 * @var array
	 */
	protected $hidden = [ 'updated_at', 'pivot' ];

	/**
	 * @var array
	 */
	protected $appends = [ 'time' ];

	/**
	 * @var array
	 */
	protected $types = [ 'reply', 'inquire', 'message', 'response' ];

	/**
	 * @type array
	 */
	protected $casts = [
		'id' => 'integer',
		'user_id' => 'integer',
		'product_id' => 'integer'
	];

	/**
	 * @type [type]
	 */
	protected $with = [ 'user' ];

	/**
	 * User relation
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function user()
	{
		return $this->belongsTo( 'Okie\User' );
	}

	/**
	 * Product relation
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
	 */
	public function product()
	{
		return $this->belongsTo( 'Okie\Product' );
	}

	/**
	 * Inquiries object in scope mode
	 *
	 * @param  mixed $query
	 *
	 * @return \Illuminate\Database\Eloquent\Builder
	 */
	public function scopeInquiriesObject( $query )
	{
		return $query->whereType( 'inquire' );
	}

	/**
	 * Inquiries in scope mode
	 *
	 * @param  mixed $query
	 *
	 * @return \Illuminate\Database\Eloquent\Builder
	 */
	public function scopeInquiries( $query )
	{
		return $query->whereType( 'inquire' )->get();
	}

	/**
	 * Get time attribute
	 *
	 * @return string
	 */
	public function getTimeAttribute()
	{
		if( $this->created_at->diffInSeconds() > 3600 )
			return $this->attributes[ 'time' ] = $this->created_at->toDayDateTimeString();
		
		return $this->attributes[ 'time' ] = $this->created_at->diffForHumans();
	}

	/**
	 * Messages by product in scope mode
	 *
	 * @param  mixed $query
	 * @param  integer $product_id
	 * @param  integer $user_id
	 *
	 * @return \Illuminate\Database\Eloquent\Builder
	 */
	public function scopeMessagesByProduct( $query, $product_id, $user_id )
	{
		return $query->whereType( 'inquire' )
					 ->whereProductId( $product_id )
					 ->whereUserId( $user_id )
					 ->latest();
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function thread()
	{
		return $this->hasMany( 'Okie\Thread', 'thread_id' );
	}

}

app/Http/Controllers/MessageController.php
<?php namespace Okie\Http\Controllers;
// TODO: This is DEPRECATED
use Okie\Http\Requests;
use Okie\Http\Controllers\Controller;
use Okie\Message;
use Auth, Event;
use Okie\Events\MessageEvent;
use Okie\Thread;
use Illuminate\Http\Request;

class MessageController extends Controller {

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware( 'auth' );
	}

	/**
	 * Inquiring an item
	 *
	 * @param  Request $request
	 *
	 * @return \Illuminate\Contracts\Routing\ResponseFactory
	 */
	public function inquireItem( Request $request )
	{
		$message = Message::create([
			'user_id' => Auth::user()->id,
			'product_id' => $request->input( 'item' ),
			'body' => $this->filterBody( $request->input( 'message' ) ),
			'type' => 'inquire'
		]);
		Event::fire( new MessageEvent( 'inquire', $message->id, Auth::user()->id, $message->product_id ) );

		return response()->json([ 'success' => [
			'message' => 'Thank you for inquiring. We will message you afterwards.',
			'data' => $message ]
		]);
	}

	/**
	 * Reply to an inquiry
	 *
	 * @param  Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function replyToInquire( Request $request )
	{
		if( Auth::user()->isAdmin() )
		{
			if( is_null( $request->input( 'item' ) ) )
			{
				$type = 'message';
			}
			else
			{
				$type = 'reply';
			}
		}
		else
		{
			$type = 'inquire';
		}
		// $type = ( Auth::user()->isAdmin() ) ? is_null( $request->input( 'item' ) ? 'message' : 'reply' : 'inquire';
		$message = Message::create([
			'user_id' => Auth::user()->id,
			'product_id' => $request->input( 'item' ),
			'body' => $this->filterBody( $request->input( 'reply' ) ),
			'type' => $type
		]);

		Event::fire( new MessageEvent( $type, $message->id, Auth::user()->id, $message->product_id, $request->input( 'thread' ) ) );

		return response()->json([ 'success' => [
			'message' => 'Successfully replied',
			'data' => $message ]
		]);
	}

	/**
	 * Get index
	 *
	 * @return \Illuminate\View\View
	 */
	public function index()
	{
		return view( 'messages.index' );
	}

	/**
	 * Get Messages view
	 *
	 * @return \Illuminate\View\View
	 */
	public function getMessagesView()
	{
		return view( 'messages.a_messages' );
	}

	/**
	 * Get Conversation view
	 *
	 * @return \Illuminate\View\View
	 */
	public function getConversationView()
	{
		return view( 'messages.a_conversation' );
	}

	/**
	 * Get Conversation delivered view
	 *
	 * @return \Illuminate\View\View
	 */
	public function getConversationDeliveredView()
	{
		return view( 'messages.a_conversation_delivered' );
	}

	/**
	 * Get Create view
	 *
	 * @return \Illuminate\View\View
	 */
	public function getCreateView()
	{
		return view( 'messages.a_create' );
	}

	/**
	 * Get Inbox view
	 *
	 * @return \Illuminate\View\View
	 */
	public function getInboxView()
	{
		return view( 'messages.a_inbox' );
	}

	/**
	 * Get Conversation inbox view
	 *
	 * @return \Illuminate\View\View
	 */
	public function getConversationInboxView()
	{
		return view( 'messages.a_conversation_inbox' );
	}

	/**
	 * Get all inquiries
	 *
	 * @return \Okie\Message
	 */
	public function getAllInquiries()
	{
		return Message::with( 'product' )->inquiriesObject()->orderBy('created_at', 'desc')->paginate();
	}

	/**
	 * Get Messages by Product
	 *
	 * @param  Request $request
	 * @param  integer  $product_id
	 *
	 * @return \Okie\Message
	 */
	public function getMessagesByProduct( Request $request, $product_id )
	{
		return Message::with( 'product' )->messagesByProduct( $product_id, $request->input( 'user' ) )->paginate();
	}

	/**
	 * Create a message
	 *
	 * @param  Request $request
	 *
	 * @return \Illuminate\Http\RedirectResponse
	 */
	public function createMessage( Request $request )
	{
		$message = Message::create([
			'user_id' => Auth::user()->id,
			'body' => $this->filterBody( $request->input( 'body' ) ),
			'type' => 'message'
		]);
		$event = Event::fire( new MessageEvent( $message->type, $message->id, Auth::user()->id, $request->input( 'subject' ), $request->input( 'user' ) ) );

		return response()->json([
			'success' => [
				'message' => 'Successfully message sent',
				'data' => [
					'message' => $message,
					'thread' => $event[1]
				]
			]
		]);
	}



}

resources/views/messages/a_conversation_deliver.blade.php
<div class="message-container conversation conversation-deliver"
    data-id="{# deliverInfo.id #}"
    data-user="{# deliverInfo.user_id #}"
    data-confirm="{# deliverInfo.confirm_id #}"
    data-product="{# deliverInfo.product_id #}"
    data-title="{# deliverInfo.title #}" ng-hide="deliverErrorState">

    @if ( Auth::user()->isPermitted() )
    <div class="marker">
        <a href="{{ route('product.index') }}/{# deliverInfo.product_id #}" target="_blank" class="btn btn-info btn-sm">VIEW PRODUCT DELIVERED</a>
    </div>
    @endif

    <div ng-class="{ 'message-same-user': (deliverConversations[ $index - 1 ].user_id == message.user_id), 'message-mine': (message.user.id == me.user.id) }" class="message-type-{# message.type.replace('deliver-', '') #} message media animate" ng-repeat="message in deliverConversations"
        data-type="{# message.type #}"
        data-id="{# message.id #}"
        data-user="{# message.user_id #}"
        data-time="{# message.time #}">
        <div class="media-left media-top">
            <a href="javascript:void(0);">
                <img ng-src="{# message.user.avatar #}" alt="avatar" class="img-circle">
            </a>
        </div>
        <div class="media-body content-description">
            <div class="message-body">
                <header class="time">{# message.time #}</header>
                <div class="message-body-content" ng-bind-html="message.body"></div>
            </div>
        </div>
    </div>

    <div class="message-reply container-fluid" id="reply">
        <alert ng-repeat="alert in alerts" type="danger" close="closeAlert( $index )"><i class="fa fa-exclamation-triangle"></i> {# alert.message #}</alert>
        {!! Form::open(['route' => 'delivered.reply', 'name' => 'form_reply', 'ng-submit' => 'form_reply.$valid && replySubmit( $event, form_reply )']) !!}
            <div serial="r3p1y" name="reply" class="content-description" ta-toolbar="[['bold', 'italics', 'underline', 'undo', 'redo', 'clear']]" ng-minlength="5" required ng-required="true" placeholder="Write a reply {{ Auth::user()->first_name }}" text-angular ng-model="reply"></div>
            <div ta-bind ng-model="reply" id="reply_bind" class="hidden"></div>
            <div class="buttons">
                <input ng-hide="replySubmitButton.state" type="submit" ng-class="{ 'btn-success': form_reply.$valid }" class="btn btn-primary" ng-disabled="form_reply.$invalid" value="SUBMIT" />
                <button ng-show="replySubmitButton.state" type="button" class="btn btn-success"><i class="fa fa-circle-o-notch fa-spin" ng-show="replySubmitButton.state"></i> SUBMITTING</button>
            </div>
        {!! Form::close() !!}
    </div>

</div>

<div class="alert alert-danger text-center" ng-show="deliverErrorState">
    <p>{# deliverErrorMessage #}</p>
</div>

resources/views/messages/a_conversation_inquiry.blade.php
<div class="message-container conversation conversation-inquiry"
    data-id="{# inquiryInfo.id #}"
    data-inquisition="{# inquiryInfo.inquisition_id #}"
    data-product="{# inquiryInfo.product_id #}"
    data-title="{# inquiryInfo.title #}" ng-hide="inquiryErrorState">

    @if ( Auth::user()->isPermitted() )
    <div class="marker">
        <a ng-class="{ inactive: inquiryStateReserve }" href="#" ng-click="moveToDelivered()" class="btn btn-info btn-sm">MARK AS DELIVERED</a>
        <a ng-class="{ inactive: inquiryStateReserve }" href="{{ route('product.index') }}/{# inquiryInfo.product_id #}" target="_blank" class="btn btn-info btn-sm">VIEW PRODUCT INQUIRED</a>
        <a ng-class="{ active: inquiryStateReserve }" href="#" ng-click="inquiryReserve( $event )" class="btn btn-info btn-sm">RESERVED ITEM</a>
        <div ng-class="{ inactive: inquiryStateReserve }" href="#" class="btn-group">
            <label class="disabled btn btn-info btn-sm">ALLOW RECEIPTS UPLOAD</label>
            <label ng-click="toggleReceiptAllowness( true )" ng-class="{ 'btn-success': inquiryInfo.uploads }" class="btn btn-default btn-sm" ng-model="inquiryInfo.uploads" btn-radio="true" uncheckable>YES</label>
            <label ng-click="toggleReceiptAllowness( false )" ng-class="{ 'btn-success': !inquiryInfo.uploads }" class="btn btn-default btn-sm" ng-model="inquiryInfo.uploads" btn-radio="false" uncheckable>NO</label>
        </div>
    </div>
    <div class="inquiry-reserve-container" ng-show="inquiryStateReserve">
        <div class="col-md-4 text-center">
            <h4 style="color:#FFF;">CURRENTLY ITEM RESERVE: {# inquiryInfo.reserve + reserve #}</h4>
        </div>
        <div class="col-md-4">
            <div class="input-group">
                <span class="input-group-btn">
                    <button type="button" ng-click="reserveButton('add')" class="btn btn-default" type="button"><i class="fa fa-plus"></i></button>
                </span>
                <input name="reserve" ng-readonly="true" type="text" class="text-center form-control" ng-model="reserve" />
                <span class="input-group-btn">
                    <button type="button" ng-click="reserveButton('minus')" class="btn btn-default" type="button"><i class="fa fa-minus"></i></button>
                </span>
                <span class="input-group-btn">
                    <button ng-click="reserveItem( reserve )" type="button" class="btn btn-primary">UPDATE</button>
                </span>
            </div>
        </div>
    </div>
    @endif

    <div ng-class="{ 'message-same-user': (inquiryConversations[ $index - 1 ].user_id == message.user_id), 'message-mine': (message.user.id == me.user.id) }" class="message-type-{# message.type.replace('inquiry-', '') #} message media animate" ng-repeat="message in inquiryConversations"
        data-type="{# message.type #}"
        data-id="{# message.id #}"
        data-user="{# message.user_id #}"
        data-time="{# message.time #}">
        <div class="media-left media-top">
            <a href="javascript:void(0);">
                <img ng-src="{# (message.type == 'inquiry-reply') ? (me.user.is_permitted) ? message.user.avatar : '{{ url('/images/logo.png') }}' : inquiryInfo.user.avatar  #}" alt="avatar" class="img-circle">
            </a>
        </div>
        <div class="media-body content-description">
            <div class="message-body">
                <header class="time">{# message.time #}</header>
                <div class="message-body-content" ng-bind-html="message.body"></div>
            </div>
        </div>
    </div>

    
    <div class="message-reply container-fluid" id="reply">
        <alert ng-repeat="alert in alerts" type="danger" close="closeAlert( $index )"><i class="fa fa-exclamation-triangle"></i> {# alert.message #}</alert>
        <div class="dropzone" id="uploadPreview" ng-if="inquiryInfo.uploads">
            <div class="upload-preview"></div>
        </div>
        <div class="upload" ng-if="inquiryInfo.uploads">
            <div ng-init="initializingDropzoneButton( inquiryInfo.id, '{{ csrf_token() }}' )"></div>
        </div>
        {!! Form::open(['route' => 'inquiry.reply', 'name' => 'form_reply', 'ng-submit' => 'form_reply.$valid && inquiryReplySubmit( $event, form_reply )']) !!}
            <div id="inquiry_reply_ta" ng-keyup="conversationShortcuts( $event, form_reply )" serial="r3p1y" name="reply" class="content-description" ta-toolbar="[['bold', 'italics', 'underline', 'undo', 'redo', 'clear']]" ng-minlength="5" required ng-required="true" placeholder="Write a reply {{ Auth::user()->first_name }}" text-angular ng-model="reply"></div>
            <div ta-bind ng-model="reply" id="reply_bind" class="hidden"></div>
            <div class="buttons">
                {{-- <span>Please enter to send <input ng-change="autoSubmit()" type="checkbox" ng-checked="autoSubmitConversation" ng-model="autoSubmitConversation"></span>&nbsp;&nbsp; --}}
                <input id="conversation_submit" ng-hide="replySubmitButton.state" type="submit" ng-class="{ 'btn-success': form_reply.$valid }" class="btn btn-primary" ng-disabled="form_reply.$invalid" value="SUBMIT" />
                <button ng-if="inquiryInfo.uploads" type="button" class="btn btn-info" ng-hide="replySubmitButton.state" id="inquiryUploadReceiptButton">UPLOAD RECEIPT</button>
                <button ng-show="replySubmitButton.state" type="button" class="btn btn-success"><i class="fa fa-circle-o-notch fa-spin" ng-show="replySubmitButton.state"></i> SUBMITTING</button>
            </div>
        {!! Form::close() !!}
        <div ng-if="inquiryInfo.uploads">
            <p><em><small>* You may upload your receipt if you're already paid. Please click the "Upload Receipt" button, or you may simply drag and drop the picture of the receipt here.</small></em></p>
        </div>
    </div>

    

    

</div>

<div class="alert alert-danger text-center" ng-show="inquiryErrorState">
    <p>{# inquiryErrorMessage #}</p>
</div>

resources/views/messages/a_messages.blade.php
<div class="message-container messages">
    <div class="alert alert-warning text-center" ng-if="! messages.length">
        <p><i class="fa fa-3x fa-exclamation-circle"></i></p>
        <p>NO {# heading | uppercase #} FOUND</p>
    </div>

    <div class="message media animate" ng-repeat="message in messages" ui-sref="messages.thread({ threadId: message.id })">
        <div class="media-left media-top">
            <a href="#" ui-sref="messages.thread({ threadId: message.id })">
                <img ng-src="{# message.product.thumbnail[2].url #}" alt="{# message.product.name #}">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">{# message.title #}<br />
                <span class="small font-light">{# message.latest.time #}</span></small>
            </h4>
            <div class="message-body" ng-bind-html="message.latest.body">
            </div>
        </div>
    </div>

</div>