app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
*/

Route::get('/', ['as' => 'index', 'uses' => 'WelcomeController@index']);

Route::get('home', 'WelcomeController@redirectHome');

get('angular-ui-notification.html', 'ViewHandlerController@angularUiNotificationView');

get(config('okie.privacy_policy.url'), 'WelcomeController@getPrivacyPolicy');
get(config('okie.terms_and_conditions.url'), 'WelcomeController@getTermsAndConditions');

Route::get('permission', 'UserController@getPermission');

Route::controller('test', 'TestController');

Route::get('/testing/force-login/{id}', 'TestController@forceLogin');

Route::get('banners', ['as' => 'banner', 'uses' => 'WelcomeController@getAllBanads']);

// Route::controllers([
//  'auth' => 'Auth\AuthController',
//  'password' => 'Auth\PasswordController',
// ]);

Route::controller('auth', 'Auth\AuthController', [
    'getLogin' => 'auth.login',
    'postLogin' => 'auth.login.post'
]);

Route::get( 'login', 'WelcomeController@redirectLogin');

Route::get('routes', 'HomeController@getAllRoutes');

Route::get('i', ['as' => 'i', 'uses' => 'UserController@getUserInfo']);

Route::get( 'login/{provider?}', ['as' => 'login.provider', 'uses' => 'Auth\AuthController@login'] );


Route::get('messages', ['as' => 'messages', 'uses' => 'HomeController@messages', 'middleware' => 'admin']);

// Route for Products
Route::resource('product', 'ProductController',
[
    'names' => [
        'create' => 'product.add'
    ]
]);
Route::match(['post', 'put', 'patch'], 'product/{product}/category', ['as' => 'product.update.category', 'uses' => 'ProductController@updateCategory']);
Route::post('product/{id}/add-image', ['as' => 'product.add_image.post', 'uses' => 'ProductController@addImagePost']);
Route::get('product/{product}/images', ['as' => 'product.images', 'uses' => 'ProductController@showImages']);
Route::get('product/views/lightbox.html', 'ProductController@getLightboxView');
Route::match(['post', 'delete'], 'product/{product}/images', ['as' => 'product.images.post', 'uses' => 'ProductController@postImages']);
Route::match(['post', 'put', 'patch'], 'product/{product}/badge', ['as' => 'product.update.badge', 'uses' => 'ProductController@updateBadge']);
Route::match(['post', 'put', 'patch'], 'product/{product}/badge/remove', ['as' => 'product.update.badge.remove', 'uses' => 'ProductController@removeBadge']);

Route::group(['prefix' => 'views'], function()
{
    // Route::get('index.html', 'WelcomeController@getIndexView');
    // Route::get('products/category.html', function(){ return view( 'product.a_category' ); });
    // Route::get('products/index.html', function(){ return view( 'product.a_index'); });
    // Route::get('settings/index.html', function(){ return view( 'settings.a_index' ); });
    get('{view}.html', 'ViewHandlerController@getIndexPublicView');

    // get('settings/{view}.html', ['uses' => 'SettingsController@getPublicView', 'middleware' => 'admin']);
    get('{type}/{view}.html', 'ViewHandlerController@getPublicView');
    // get('messages/messages.html', 'MessageController@getMessagesView');
    // get('messages/conversation.html', 'MessageController@getConversationView');
    // get('messages/conversation_delivered.html', 'MessageController@getConversationDeliveredView');
    // get('messages/create.html', 'MessageController@getCreateView');
    
});

Route::group(['prefix' => 'search'], function()
{
    Route::get('user/{search?}', ['as' => 'search.user', 'uses' => 'SearchController@getUser']);
    Route::get('product/{search?}', ['as' => 'search.product', 'uses' => 'SearchController@getProduct']);
});

Route::post('newsletter', ['as' => 'newsletter', 'uses' => 'NewsletterController@subscribeToNewsletter']);
Route::get('newsletter', ['as' => 'newsletter.user', 'uses' => 'NewsletterController@getSubscribeByUser']);

Route::group(['prefix' => 'me', 'middleware' => 'auth'], function()
{
    Route::get('/', ['as' => 'me', 'uses' => 'UserController@getUserInfo']);
    Route::get('friends', ['as' => 'me.friends', 'uses' => 'UserController@getFriendsList']);
    Route::get('banners', ['as' => 'me.banners', 'uses' => 'OptionController@getAllBanads']);
    Route::get('views/{view}.html', 'ViewHandlerController@getMessagesView');
    Route::group(['prefix' => 'settings'], function()
    {
        Route::get('/', ['as' => 'settings.index', 'uses' => 'SettingsController@index']);
        Route::post('newsletter', ['as' => 'settings.newsletter.unsubscribe', 'uses' => 'NewsletterController@unsubscribeEmail']);
        Route::patch('permissions', ['as' => 'settings.permissions', 'uses' => 'SettingsController@changeUserPermission']);
        Route::post('general', ['as' => 'settings.general', 'uses' => 'OptionController@updateAppConfig']);
        Route::get('banners', ['as' => 'settings.banners', 'uses' => 'OptionController@getAllBanads']);
        Route::post('banner', ['as' => 'settings.banner', 'uses' => 'OptionController@addBanner']);
        Route::delete('banner/{id}', ['as' => 'settings.banner.delete', 'uses' => 'OptionController@removeBanad']);
    });
    Route::group(['prefix' => 'products'], function()
    {
        Route::get('/', ['as' => 'products.index', 'uses' => 'ProductController@index']);
        Route::get('categories', ['as' => 'products.categories', 'uses' => 'CategoryController@getCategories']);
        Route::post('categories', ['as' => 'products.categories.post', 'uses' => 'CategoryController@postCategory']);
    });
    Route::group(['prefix' => 'messages'], function()
    {
        Route::get('/', ['as' => 'messages.index', 'uses' => 'MessageController@index']);
        Route::get('offset', ['as' => 'messages.offset', 'uses' => 'ThreadController@getMessagesByOffset']);
        Route::post('create', ['as' => 'messages.create', 'uses' => 'MessageController@createMessage']);
        Route::group(['prefix' => 'inquiry'], function()
        {
            get('all', ['as' => 'inquiry.all', 'uses' => 'InquiryController@getAll']);
            get('{inquiry_id}', ['as' => 'inquiry', 'uses' => 'InquiryController@get']);
            get('{inquiry_id}/conversations', ['as' => 'inquiry.conversations', 'uses' => 'InquiryController@getConversations']);
            post('reply', ['as' => 'inquiry.reply', 'uses' => 'InquiryController@reply']);
            post('replyReceipt', ['as' => 'inquiry.replyReceipt', 'uses' => 'InquiryController@replyReceipt']);
            post('reserve', ['as' => 'inquiry.reserve', 'uses' => 'InquiryController@postReserve']);
            post('delivered', ['as' => 'inquiry.delivered', 'uses' => 'DeliverController@create']);
            post('receipt', ['as' => 'inquiry.receipt', 'uses' => 'InquiryController@toggleUpload']);
            get('product/{product_id}', ['as' => 'inquiry.product', 'uses' => 'InquiryController@getInquiryByProduct']);
        });
        Route::group(['prefix' => 'inbox'], function()
        {
            get('/', ['as' => 'messages.inbox', 'uses' => 'InboxController@getAll']);
            get('all', ['as' => 'inbox.all', 'uses' => 'InboxController@getAll']);
            get('{inbox_id}', ['as' => 'inbox', 'uses' => 'InboxController@get']);
            get('{inbox_id}/conversations', ['as' => 'inbox.conversations', 'uses' => 'InboxController@getConversations']);
            post('reply', ['as' => 'inbox.reply', 'uses' => 'InboxController@reply']);
            post('create', ['as' => 'inbox.create', 'uses' => 'InboxController@create']);
            post('{conversation_id}/delete', ['as' => 'inbox.remove.conversation', 'uses' => 'InboxController@destroyConversation']);
        });
        Route::group(['prefix' => 'delivered'], function()
        {
            get('/', ['as' => 'messages.delivered', 'uses' => 'DeliverController@getAll']);
            get('all', ['as' => 'delivered.all', 'uses' => 'DeliverController@getAll']);
            get('{delivered_id}', ['as' => 'delivered', 'uses' => 'DeliverController@get']);
            get('{delivered_id}/conversations', ['as' => 'delivered.conversations', 'uses' => 'DeliverController@getConversations']);
            post('reply', ['as' => 'delivered.reply', 'uses' => 'DeliverController@reply']);
        });
        Route::get('inquiries', ['as' => 'messages.inquiries', 'uses' => 'InquiryController@getAll']);
        // Route::get('inquire/{thread_id}', ['as' => 'messages.inquiries.thread', 'uses' => 'ThreadController@getInquiryByThread']);
        // Route::get('inquire/{thread_id}/messages', ['as' => 'messages.inquiries.thread.messages', 'uses' => 'ThreadController@getMessagesByThread']);
        // Route::post('inquire/reply', ['as' => 'messages.inquiries.reply', 'uses' => 'MessageController@replyToInquire']);
        // Route::post('inquire/delivered', ['as' => 'messages.inquiries.delivered', 'uses' => 'ThreadController@updateToDelivered']);

        //Route::get('delivered', ['middleware' => 'admin', 'as' => 'messages.delivered', 'uses' => 'ThreadController@getAllDelivered']);
    });
    Route::group(['prefix' => 'reviews'], function()
    {
        get('/', ['as' => 'reviews.index', 'uses' => 'ReviewController@getAll']);
        post('{id}/approved', ['as' => 'reviews.approved', 'uses' => 'ReviewController@approvedReview']);
        post('{id}/unapproved', ['as' => 'reviews.unapproved', 'uses' => 'ReviewController@unapprovedReview']);
    });
});

Route::group(['prefix' => 'items'], function()
{
    Route::get('/', ['as' => 'items.index', 'uses' => 'ItemController@index']);
    Route::get('/{id}', ['as' => 'items.item', 'uses' => 'ItemController@show'])->where( 'id', '[0-9]+' );
    Route::get('/category/{id}', ['as' => 'items.category', 'uses' => 'ItemController@showByCategory']);
});

Route::group(['prefix' => 'item'], function()
{
    get('/{id}', ['as' => 'item.show', 'uses' => 'ItemController@show']);

resources/views/templates/container-loading.blade.php
<div id="container_loading"></div>

resources/views/templates/footer.blade.php
<footer id="footer" class="footer">

    <div class="container-fluid clearfix">
        <div class="col-md-5">
            <div class="panel panel-default company-footer _widget_company-footer _widget _footer_widget" data-widget="company-footer">
                <div class="panel-heading">
                    <h2 class="panel-title">{{ strtoupper( config('app.title') ) }}</h2>
                </div>
                <div class="panel-body clearfix row">
                    <div class="col-xs-5 col-md-4">
                        <img src="{{ config('app.logo.img') }}" alt="logo" class="img-responsive" />
                    </div>
                    <div class="col-xs-7 col-md-8 external-links">
                        <ul class="list-unstyled content-description">
                            <li>{{ config('app.description') }}</li>
                            <li>{{ config('app.url') }}/</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div data-widget="recent-items" class="_widget_recent-items _widget _footer_widget panel panel-default recent-items">
                <div class="panel-heading">
                    <h3 class="panel-title">FEATURED ITEMS</h3>
                </div>
                <div class="panel-body">
                    @if ( ! $products->isEmpty() )
                    <ul class="list-unstyled">
                    @foreach ( $products as $key => $product )
                        @if( $product->images()->exists() )
                        <li class="product-item">
                            <a href="{{ route('index') }}{# $state.href('item', { itemId: {{ $product->id }} }) #}">
                                <img src="{{ $product->thumbnail[1]['url'] }}" alt="{{ $product->name }}" />
                            </a>
                        </li>
                        @endif
                    @endforeach
                    </ul>
                    @else
                    <div class="alert alert-warning">
                        <h3 class="no-margin">NO FEATURED ITEMS AS OF THE MOMENT</h3>
                    </div>
                    @endif
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-default _widget_contact-us _widget _footer_widget contact-us" data-widget="contact-us">
                <div class="panel-heading">
                    <h2 class="panel-title">CONTACT US</h2>
                </div>
                <div class="panel-body clearfix row">
                    <div class="external-links">
                        <ul class="list-unstyled content-description">
                            <li>
                                <span class="fa-stack fa-lg icon">
                                    <i class="fa fa-circle-o fa-stack-2x"></i>
                                    <i class="fa fa-map-marker fa-stack-1x fa-inverse"></i>
                                </span>
                                {{ config('app.address') }}
                            </li>
                            <li>
                                <span class="fa-stack fa-lg icon">
                                    <i class="fa fa-circle-o fa-stack-2x"></i>
                                    <i class="fa fa-phone fa-stack-1x fa-inverse"></i>
                                </span>
                                {{ config('app.contact.phone') }}
                            </li>
                            <li>
                                <span class="fa-stack fa-lg icon">
                                    <i class="fa fa-circle-o fa-stack-2x"></i>
                                    <i class="fa fa-mobile fa-stack-1x fa-inverse"></i>
                                </span>
                                {{ config('app.contact.mobile') }}
                            </li>
                            <li>
                                <span class="fa-stack fa-lg icon">
                                    <i class="fa fa-circle-o fa-stack-2x"></i>
                                    <i class="fa fa-at fa-stack-1x fa-inverse"></i>
                                </span>
                                <a href="mailto:{{ config('mail.support') }}">{{ config('mail.support') }}</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="text-center copyright content-serif">
        {{ config( 'app.footer' ) }} &bull; <a href="{{ config( 'okie.privacy_policy.url' ) }}">Privacy Policy</a> &bull; <a href="{{ config( 'okie.terms_and_conditions.url' ) }}">Terms and Conditions</a>
    </div>
</footer>

resources/views/templates/google-analytics-snippets.blade.php
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '{{ config( 'services.google.analytics.tracking_id' ) }}', 'auto');
  ga('send', 'pageview');

</script>

resources/views/templates/heading.blade.php
<div class="heading container-fluid">
	
	
</div>

resources/views/templates/item-carousel.blade.php
<div id="item-carousel-carousel" data-ride="carousel" class="carousel slide item-carousel-slide">
    <!-- Indicators -->
  <ol class="carousel-indicators">
    @foreach ($images as $key => $value)
      <li data-target="#item-carousel-carousel" data-slide-to="{{ $key }}" @if( $key == 0 ) class="active" @endif></li>
    @endforeach
  </ol>
    <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    @foreach ($images as $key => $value)
    <div class="item" @if( $key == 0 ) class="active" @endif>
      <img src="{{ $value->sizes[2]['url'] }}" alt="{{ $value->caption }}" />
    </div>
    @endforeach
  </div>
    <!-- Controls -->
  <a class="left carousel-control" href="#item-carousel-carousel" role="button">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#item-carousel-carousel" role="button">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

resources/views/templates/js-routes.blade.php
<script type="text/javascript">
window._url = {
   'inquiry': {
        'all': '{{ route( 'messages.inquiries' ) }}',
        'find': '{{ route( 'inquiry', '_INQUIRY_ID_' ) }}',
        'conversations': '{{ route( 'inquiry.conversations', '_INQUIRY_ID_' ) }}',
        'reply': '{{ route( 'inquiry.reply' ) }}',
        'delivered': '{{ route( 'inquiry.delivered' ) }}',
        'reserve': '{{ route( 'inquiry.reserve' ) }}',
        'replyReceipt': '{{ route( 'inquiry.replyReceipt' ) }}'
        @if ( Auth::user()->isPermitted() )
        ,'byProduct': '{{ route( 'inquiry.product', '_INQUIRY_ID_' ) }}'
        ,'receiptAllowness': '{{ route( 'inquiry.receipt' ) }}'
        @endif
   },
   'inbox': {
        'all': '{{ route( 'messages.inbox' ) }}',
        'conversations': '{{ route( 'inbox.conversations', '_INQUIRY_ID_' ) }}',
        'find': '{{ route( 'inbox', '_INQUIRY_ID_' ) }}',
        'reply': '{{ route( 'inbox.reply' ) }}'
        @if( Auth::user()->isAdmin() )
        ,'removeConversation': '{{ route( 'inbox.remove.conversation', '_CONVERSATION_ID_' ) }}'
        @endif
   },
   'settings': {
        'unsubscribeNewsletter': '{{ route( 'settings.newsletter.unsubscribe' ) }}'
        @if ( Auth::user()->isAdmin() )
        ,'users': '{{ route( 'me.friends' ) }}'
        ,'permissions': '{{ route ( 'settings.permissions' ) }}'
        ,'general': '{{ route( 'settings.general' ) }}'
        ,'banner': '{{ route( 'settings.banner' ) }}'
        ,'deleteBanner': '{{ route( 'settings.banner.delete', '_BANNER_ID_' ) }}'
        @endif
   }
@if ( Auth::user()->isPermitted() )
  ,'deliver': {
    'all': '{{ route( 'messages.delivered' ) }}',
    'find': '{{ route( 'delivered', '_DELIVER_ID_' ) }}',
    'conversations': '{{ route( 'delivered.conversations', '_DELIVER_ID_' ) }}',
    'reply': '{{ route( 'delivered.reply' ) }}'
  }
  ,'products': {
    'all': '{{ route( 'products.index' ) }}',
    'updateCategory': '{{ route( 'product.update.category', '_PRODUCT_ID_' ) }}',
    'update': '{{ route( 'product.update', '_PRODUCT_ID_' ) }}',
    'destroy': '{{ route( 'product.destroy', '_PRODUCT_ID_' ) }}',
    'updateBadge': '{{ route( 'product.update.badge', '_PRODUCT_ID_' ) }}'
  }
  ,'reviews': {
    'all': '{{ route( 'reviews.index' ) }}',
    'approved': '{{ route( 'reviews.approved', '_REVIEW_ID_' ) }}',
    'unapproved': '{{ route( 'reviews.unapproved', '_REVIEW_ID_' ) }}'
  }
@endif
}
</script>

resources/views/templates/navigation-categories.blade.php
<nav class="navbar-category hidden-md hidden-lg" id="category_nav_nav">
    <div class="container-fluid">
        <div class="navbar-header text-center">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#category_nav">
                <span>CATEGORIES</span>
                <span class="nav-down fa fa-angle-down"></span>
                <span class="nav-up fa fa-angle-up"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="category_nav">
            <ul class="nav nav-pills nav-justified">
                <li class="parent" ng-class="{ active: $state.is('index') }">
                    <a href="{{ route('index') }}/#/">ALL</a>
                </li>
                @foreach ( $categories as $key => $value )
                    @if( $value->navigation )
                        @if ( is_bool( $value->parent ) )
                            @if ( ! empty( $value->children ) )
                                {{-- */ $length = count( $value->children) /* --}}
                                <li class="dropdown parent">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">{{ strtoupper( $value->name ) }} 
                                        <span class="label label-default" ng-show="
                                        @foreach ($value->children as $childKey => $childValue)
                                            @if ( $childKey == $length - 1 )
                                                ( $stateParams.categoryId == {{ $childValue->id }} || $stateParams.categoryId == '{{ $childValue->slug }}' )
                                            @else
                                                ( $stateParams.categoryId == {{ $childValue->id }} || $stateParams.categoryId == '{{ $childValue->slug }}' ) ||
                                            @endif
                                        @endforeach
                                        ">{# categoryInfo.name | uppercase #}</span>
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        @foreach ( $value->children as $childKey => $childValue )
                                            <li ng-class="{ active: ( $stateParams.categoryId == {{ $childValue->id }} || $stateParams.categoryId == '{{ $childValue->slug }}' ) }">
                                                <a href="/#/category/{{ $childValue->slug }}">{{ strtoupper( $childValue->name ) }}</a>
                                            </li>
                                        @endforeach
                                    </ul>
                                   
                                </li>
                            @else
                                <li class="parent" ng-class="{ active: ( $stateParams.categoryId == {{ $value->id }} || $stateParams.categoryId == '{{ $value->slug }}' ) }">
                                    <a href="/#/category/{{ $value->slug }}">{{ strtoupper( $value->name ) }}</a>
                                </li>
                            @endif
                        @endif
                    @endif
                @endforeach
            </ul>
        </div>
    </div>
</nav>

resources/views/templates/navigation.blade.php
<ul id="navbar_navigation" class="nav navbar-nav visible-md visible-lg affected-with-okie-search">
	@foreach ( $categories as $key => $value )
        @if( $value->navigation )
            @if ( is_bool( $value->parent ) )
                @if ( ! empty( $value->children ) )
                {{-- */ $length = count( $value->children) /* --}}
                    <li class="dropdown parent"
                    ng-class="{
                    active: (
                    @foreach ( $value->children as $childKey => $childValue )
                    $stateParams.categoryId == '{{ $childValue->slug }}' ||
                    @endforeach
                    $stateParams.categoryId == '{{ $value->slug }}')
                    }">
                        <a class="dropdown-toggle collapsed" data-toggle="collapse" href="#collapse-{{ str_slug( $value->name ) }}" role="button" aria-expanded="false">{{ strtoupper( $value->name ) }} 
                            <span class="caret"></span>
                        </a>
                        <div id="collapse-{{ str_slug( $value->name ) }}" class="collapse collapse-navigation">
                            <ul class="nav nav-pills nav-justified" role="menu">
                                @foreach ( $value->children as $childKey => $childValue )
                                    @if( $childValue->navigation )
                                    <li ng-class="{ active: ( $stateParams.categoryId == {{ $childValue->id }} || $stateParams.categoryId == '{{ $childValue->slug }}' ) }">
                                        <a href="{{ route('index') }}{# $state.href( 'category', { categoryId: '{{ $childValue->slug }}' } ) #}">{{ strtoupper( $childValue->name ) }}</a>
                                    </li>
                                    @endif
                                @endforeach
                            </ul>
                        </div>
                    </li>
                @else
                    <li ng-click="collapseToggle()" class="parent" ng-class="{ active: ( $stateParams.categoryId == {{ $value->id }} || $stateParams.categoryId == '{{ $value->slug }}' ) }">
                        <a href="/#/category/{{ $value->slug }}">{{ strtoupper( $value->name ) }}</a>
                    </li>
                @endif
            @endif
        @endif
    @endforeach
</ul>

resources/views/templates/profile.blade.php
@extends('app')

@section('title', ' - Profile')

@section('content')

<div class="container-fluid profile-container content-container" @yield('profile.attr')>
    <div class="profile-full-name" ng-bind-html="heading">
        @yield('settings.heading', Auth::user()->getFullName() . "<span>'s profile</span>")
    </div>
    <div class="profile-left col-md-3">
        <div class="profile-block">
            <a class="profile-photo" href="{{ route('me') }}">
                <img src="{{ Auth::user()->avatar }}" alt="profile" class="img-circle" />
            </a>
        </div>
        <hr class="clearfix" />
        <div class="profile-navigation">
            @include('templates.profile-navigation')
        </div>
    </div>
    <div class="profile-right profile-content col-md-9">
        @yield('settings.content')
    </div>
</div>

@endsection

@section( 'head.post' )
@include( 'templates.js-routes' )

@stop